create table if not exists public.suites (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  price numeric(12,2) not null,
  capacity int not null,
  main_image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.amenities (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon_key text,
  created_at timestamptz not null default now()
);

create table if not exists public.suite_amenities (
  id bigint generated by default as identity primary key,
  suite_id bigint not null references public.suites(id) on delete cascade,
  amenity_id bigint not null references public.amenities(id) on delete restrict,
  unique (suite_id, amenity_id)
);

create table if not exists public.suite_images (
  id bigint generated by default as identity primary key,
  suite_id bigint not null references public.suites(id) on delete cascade,
  url text not null,
  position int,
  created_at timestamptz not null default now()
);

create index if not exists suite_images_suite_id_position_idx on public.suite_images(suite_id, position);
create index if not exists suite_amenities_suite_id_idx on public.suite_amenities(suite_id);
create index if not exists suites_price_idx on public.suites(price);
create index if not exists suites_capacity_idx on public.suites(capacity);

alter table public.suites disable row level security;
alter table public.amenities disable row level security;
alter table public.suite_amenities disable row level security;
alter table public.suite_images disable row level security;

select storage.create_bucket('suites', public := true);

